#|
 This file is a part of iclendar
 (c) 2018 Shirakumo http://tymoon.eu (shinmera@tymoon.eu)
 Author: Nicolas Hafner <shinmera@tymoon.eu>
|#

(in-package #:org.shirakumo.iclendar)

(define-block calendar ()
    ((components :identifier NIL :requirement :multiple)
     (method :identifier "METHOD" :requirement :optional)
     (product :identifier "PRODID" :requirement :required)
     (scale :identifier "CALSCALE" :requirement :optional)
     (version :identifier "VERSION" :requirement :required))
  (:identifier . "VCALENDAR"))

(define-block component ()
    ((extensions :identifier NIL :requirement :multiple)
     (iana :identifier NIL :requirement :multiple)))

(define-block calendar-component (component)
    ((attendees :identifier "ATTENDEE" :requirement :multiple)
     (comments :identifier "COMMENT" :requirement :multiple)
     (request-status :identifier "REQUEST-STATUS" :requirement :multiple)
     (stamp :identifier "DTSTAMP" :requirement :required)
     (start :identifier "DTSTART" :requirement (not method))
     (uid :identifier "UID" :requirement :required)
     (url :identifier "URL" :requirement :optional)))

(define-block date-component (calendar-component)
    ((attachments :identifier "ATTACH" :requirement :multiple)
     (categories :identifier "CATEGORIES" :requirement :multiple)
     (class :identifier "CLASS" :requirement :optional)
     (contacts :identifier "CONTACT" :requirement :multiple)
     (created :identifier "CREATED" :requirement :optional)
     (exception-dates :identifier "EXDATE" :requirement :multiple)
     (last-modification :identifier "LAST-MODIFIED" :requirement :optional)
     (organizer :identifier "ORGANIZER" :requirement :optional)
     (recurrence-dates :identifier "RDATE" :requirement :multiple)
     (recurrence :identifier "RECURRENCE-ID" :requirement :optional)
     (related :identifier "RELATED-TO" :requirement :optional)
     (resources :identifier "RESOURCES" :requirement :multiple)
     (recurrence-rule :identifier "RRULE" :requirement :optional)
     (sequence-number :identifier "SEQUENCE" :requirement :optional)
     (status :identifier "STATUS" :requirement :optional)
     (summary :identifier "SUMMARY" :requirement :optional)))

(define-block task-component (date-component)
    ((description :identifier "DESCRIPTION" :requirement :optional)
     (duration :identifier "DURATION" :requirement :optional)
     (geographic-location :identifier "GEO" :requirement :optional)
     (location :identifier "LOCATION" :requirement :optional)
     (priority :identifier "PRIORITY" :requirement :optional)))

(define-block event (task-component)
    ((end :identifier "DTEND" :requirement (not duration))
     (duration :identifier "DURATION" :requirement (not end))
     (transparency :identifier "TRANSP" :requirement :optional))
  (:identifier . "VEVENT"))

(define-block todo (task-component)
    ((completed :identifier "COMPLETED" :requirement :optional)
     (completeness :identifier "PERCENT-COMPLETE" :requirement :optional)
     (due :identifier "DUE" :requirement (not duration))
     (duration :identifier "DURATION" :requirement (not due)))
  (:identifier . "VTODO"))

(define-block journal (date-component)
    ()
  (:identifier . "VJOURNAL"))

(define-block free/busy (calendar-component)
    ((contact :identifier "CONTACT" :requirement :optional)
     (end :identifier "DTEND" :requirement :optional)
     (free/busy :identifier "FREEBUSY" :requirement :multiple)
     (organizer :identifier "ORGANIZER" :requirement :optional))
  (:identifier . "VFREEBUSY"))

(define-block time-zone (component)
    ((tzid :identifier "TZID" :requirement :required)
     (last-modification :identifier "LAST-MODIFIED" :requirement :optional)
     (tzurl :identifier "TZURL" :requirement :optional)
     (components :identifier NIL :requirement :multiple))
  (:identifier . "VTIMEZONE"))

(define-block alarm (component)
    ((action :identifier "ACTION" :requirement :required)
     (trigger :identifier "TRIGGER" :requirement :required)
     (duration :identifier "DURATION" :requirement repeat)
     (repeat :identifier "REPEAT" :requirement duration))
  (:identifier . "VALARM"))

(define-block audio-alarm (alarm)
    ((attachment :identifier "ATTACH" :requirement :optional)))

(define-block display-alarm (alarm)
    ((description :identifier "DESCRIPTION" :requirement :required)))

(define-block email-alarm (alarm)
    ((attachments :identifier "ATTACH" :requirement :multiple)
     (description  :identifier "DESCRIPTION" :requirement :required)
     (summary :identifier "SUMMARY" :requirement :required)
     (attendees :identifier "ATTENDEE" :requirement :multiple)))

(define-block time-zone-component (component)
    ((start :identifier "DTSTART" :requirement :required)
     (offset-to :identifier "TZOFFSETTO" :requirement :required)
     (offset-from :identifier "TZOFFSETFROM" :requirement :required)
     (recurrence-rule :identifier "RRULE" :requirement :optional)
     (comments :identifier "COMMENT" :requirement :multiple)
     (recurrence-dates :identifier "RDATE" :requirement :multiple)
     (tznames :identifier "TZNAME" :requirement :multiple)))

(define-block time-zone-standard (time-zone-component)
    ()
  (:identifier . "STANDARD"))

(define-block time-zone-daylight (time-zone-component)
    ()
  (:identifier . "DAYLIGHT"))

(define-block iana (component)
    ())

(define-block extension (component)
    ())
